package org.wai.flyway.sample.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.wai.flyway.sample.entity.Employee;

/**
 * Class _Address was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Address extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String COUNTRY_PROPERTY = "country";
    public static final String POSTCODE_PROPERTY = "postcode";
    public static final String STATE_PROPERTY = "state";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String ID_PK_COLUMN = "id";

    public void setAddress(String address) {
        writeProperty("address", address);
    }
    public String getAddress() {
        return (String)readProperty("address");
    }

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setPostcode(String postcode) {
        writeProperty("postcode", postcode);
    }
    public String getPostcode() {
        return (String)readProperty("postcode");
    }

    public void setState(String state) {
        writeProperty("state", state);
    }
    public String getState() {
        return (String)readProperty("state");
    }

    public void setEmployee(Employee employee) {
        setToOneTarget("employee", employee, true);
    }

    public Employee getEmployee() {
        return (Employee)readProperty("employee");
    }


}
