package org.wai.flyway.sample.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.wai.flyway.sample.entity.Address;
import org.wai.flyway.sample.entity.Project;

/**
 * Class _Employee was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Employee extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String POSITION_PROPERTY = "position";
    public static final String ADDRESS_PROPERTY = "address";
    public static final String PROJECT_PROPERTY = "project";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPosition(String position) {
        writeProperty("position", position);
    }
    public String getPosition() {
        return (String)readProperty("position");
    }

    public void setAddress(Address address) {
        setToOneTarget("address", address, true);
    }

    public Address getAddress() {
        return (Address)readProperty("address");
    }


    public void setProject(Project project) {
        setToOneTarget("project", project, true);
    }

    public Project getProject() {
        return (Project)readProperty("project");
    }


}
