package org.wai.flyway.sample.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.wai.flyway.sample.entity.Employee;

import java.util.List;

/**
 * Class _Project was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Project extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String EMPLOYEE_PROPERTY = "employee";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToEmployee(Employee obj) {
        addToManyTarget("employee", obj, true);
    }
    public void removeFromEmployee(Employee obj) {
        removeToManyTarget("employee", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Employee> getEmployee() {
        return (List<Employee>)readProperty("employee");
    }


}
